# Generated by Django 4.0.5 on 2022-06-27 05:13

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_user_is_cctv_user_is_gate'),
    ]

    operations = [
        migrations.CreateModel(
            name='gatekeepers',
            fields=[
            ],
            options={
                'verbose_name': 'GATEkeeper',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('start.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'All User'},
        ),
    ]
