# Generated by Django 4.0.5 on 2022-06-27 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0002_parking_slots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Vehicle Categorie'},
        ),
        migrations.AlterModelOptions(
            name='parking_slots',
            options={'verbose_name': 'Parking Slots- Statu'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='slot',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryname',
            field=models.CharField(max_length=50, verbose_name='Vehicle Category'),
        ),
        migrations.AlterField(
            model_name='parking_slots',
            name='Total_Slots',
            field=models.IntegerField(default=20, verbose_name='Total slots'),
        ),
        migrations.AlterField(
            model_name='parking_slots',
            name='parked',
            field=models.IntegerField(default=0, verbose_name='Parked slots'),
        ),
        migrations.AlterField(
            model_name='parking_slots',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gate'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ownercontact',
            field=models.CharField(max_length=15, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pdate',
            field=models.DateTimeField(verbose_name='Parking Date'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='regno',
            field=models.CharField(max_length=10, verbose_name='Registration Number'),
        ),
    ]
