# Generated by Django 4.0.5 on 2022-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_category_options_alter_parking_slots_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='regno',
            field=models.CharField(max_length=17, verbose_name='Registration Number'),
        ),
    ]
