# Generated by Django 4.0.5 on 2022-07-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_vehicle_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(default=0)),
                ('gate', models.CharField(default='gate1', max_length=8)),
                ('slot', models.IntegerField(default=-1)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
