# Generated by Django 4.0.4 on 2022-06-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rid',
            field=models.IntegerField(default=-1),
        ),
    ]
