# Generated by Django 4.0.4 on 2022-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_user1_order_payment_alter_customer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.DeleteModel(
            name='User1',
        ),
    ]
