# Generated by Django 4.0.5 on 2022-06-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_order_payment_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='img',
            field=models.ImageField(default='0ade14b6-8937-43ea-93eb-98343af6bae7___JR_HL_8026.JPG', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
