# Generated by Django 4.0.5 on 2022-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_item_img_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='min_ord',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
