# Generated by Django 4.0.5 on 2022-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_remove_restaurant_min_ord_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.IntegerField(),
        ),
    ]
