# Generated by Django 4.0.5 on 2022-06-27 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='f_name',
            field=models.CharField(max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='l_name',
            field=models.CharField(max_length=20, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(unique=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rid',
            field=models.IntegerField(default=-1, verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.item', verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_addr',
            field=models.IntegerField(blank=True, default=-1, verbose_name='Table Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='r_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.IntegerField(default=0, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='info',
            field=models.CharField(max_length=40, verbose_name='Restaurant Info'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rname',
            field=models.CharField(max_length=100, verbose_name='Restaurant'),
        ),
    ]
