# Generated by Django 4.0.5 on 2022-06-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_customer_f_name_alter_customer_l_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rname',
            field=models.CharField(max_length=20, verbose_name='Restaurant'),
        ),
    ]
