# Generated by Django 4.0.5 on 2022-07-01 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_restaurant_location_alter_restaurant_rname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=200)),
                ('about_rest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.restaurant')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.customer')),
            ],
        ),
    ]
