# Generated by Django 4.0.5 on 2022-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='secret_code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='fname',
            field=models.CharField(max_length=30, verbose_name='Item'),
        ),
    ]
