# Generated by Django 4.0.5 on 2022-07-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_order_secret_code_alter_item_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.BooleanField(default=False),
        ),
    ]
